languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "Cuttontail"
#logo = "img/logo.png"
description = "前端、设计和让自己眼前一亮的想法"
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2006-01-02"

[author]
  name = "小綿尾巴"
  image = "img/avatar.jpg"
  # headline = "I'm only human"
  bio = "正在路上的前端工程师"
  links = [
    { github = "https://github.com/miawithcode" },
    { twitter = "https://twitter.com/cuttontailc" },
    { telegram = "https://t.me/cuttontail" },
    { email = "mailto:cuttontail@gmail.com" },
   ]