# .github/workflows/douban.yml
name: douban
on: 
  schedule:
    - cron: "* 8 * * *"
  push:
    branches:
      - blog
  

jobs:
  douban:
    name: Douban mark data sync
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: notion_movie
      uses: lizheming/doumark-action@master
      with:
        id: 60029335
        type: movie
        format: notion
        dir: a30a1c79e62a4d33bb10ee8ec5dd4588
        notion_token: ${{ secrets.notion_token }}
        
    - name: notion_book
      uses: lizheming/doumark-action@master
      with:
        id: 60029335
        type: book
        format: notion
        dir: a30a1c79e62a4d33bb10ee8ec5dd4588
        notion_token: ${{ secrets.notion_token }}