# .github/workflows/douban.yml
name: douban
on: 
  schedule:
    - cron: "* 8 * * *"
  push:
    branches:
      - blog
  

jobs:
  douban:
    name: Douban mark data sync
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Sync Movies To Notion
      uses: lizheming/doumark-action@master
      with:
        id: 60029335
        type: movie
        format: notion
        dir: f6f7cff6860045d9917215b09ab72029
        notion_token: ${{ secrets.notion_token }}
        
    - name: Sync Books To Notion
      uses: lizheming/doumark-action@master
      with:
        id: 60029335
        type: book
        format: notion
        dir: 20512657dba644609ddab57a3cf594ff
        notion_token: ${{ secrets.notion_token }}

    - name: Sync Movies To Local
      uses: lizheming/doumark-action@master
      with:
        id: 60029335
        type: movie
        format: json
        dir: ./data/doubanSync

    - name: Sync Books To Local
      uses: lizheming/doumark-action@master
      with:
        id: 60029335
        type: book
        format: json
        dir: ./data/doubanSync