# .github/workflows/douban.yml
name: douban
on: 
  schedule:
  - cron: "30 * * * *"

jobs:
  douban:
    name: Douban mark data sync
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: movie
      uses: lizheming/doumark-action@master
      with:
        id: 60029335
        type: movie
        format: json
        dir: ./data/douban-sync

    - name: book
      uses: lizheming/doumark-action@master
      with:
        id: 60029335
        type: book
        format: json
        dir: ./data/douban-sync
  
    - name: Commit
      uses: EndBug/add-and-commit@v8
      with:
        message: 'chore: update douban data'
        add: './data/douban-sync'