# .github/workflows/douban.yml
name: douban
on: 
  schedule:
  - cron: "* 30 12 * * *"

jobs:
  douban:
    name: Douban mark data sync
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: movie
      uses: lizheming/doumark-action@master
      with:
        id: 60029335
        type: movie
        format: csv
        dir: ./data/doubanSync

    - name: book
      uses: lizheming/doumark-action@master
      with:
        id: 60029335
        type: book
        format: csv
        dir: ./data/doubanSync
  
    - name: Commit
      uses: EndBug/add-and-commit@v8
      with:
        message: 'Update Douban Data By Github Action'
        add: './data/doubanSync'