name: Douban
on: 
  # schedule:
  # - cron: "0 0,0,12,23 * * *"
  # watch:
  #   types: [started]
  push:
    branches:
      - blog

jobs:
  douban:
    name: Sync Douban Data
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
        architecture: "x64"
    - name: Run Generator
      run: |
          sudo mkdir -p /home/runner/work/
          cd /home/runner/work/
          sudo git clone https://github.com/qinyuanpei/douban-generator.git 
          cd /home/runner/work/douban-generator
          sudo rm -rf /usr/bin/python
          sudo ln -s /usr/bin/python3  /usr/bin/python
          sudo python --version
          sudo python -m pip install pip -U
          sudo python -m pip config set global.index-url http://mirrors.aliyun.com/pypi/simple/
          sudo python -m pip config set install.trusted-host mirrors.aliyun.com
          STATIC_DEPS=true pip install lxml 
          sudo python -m pip install requests
          sudo python -m pip install -r requirements.txt 
          python movies-generator.py 60029335
          python books-generator.py 60029335
          python games-generator.py 60029335
    # - name: Auto Commit
    #   uses: EndBug/add-and-commit@v8
    #   with:
    #     message: 'Update Douban Data'
    #     add: ./themes/hugo-theme-stack/data/