name: douban
on: 
  # schedule:
  # - cron: "0 0,0,12,23 * * *"
  # watch:
  #   types: [started]
  push:
    branches:
      - blog

jobs:
  douban:
    name: Syna Douban Data
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Sync Movies
      uses: lizheming/doumark-action@master
      with:
        id: qinyuanpei
        type: movie
        format: json
        dir: ./data/douban

    - name: book
      uses: lizheming/doumark-action@master
      with:
        id: qinyuanpei
        type: book
        format: json
        dir: ./data/douban
  
    - name: Commit
      uses: EndBug/add-and-commit@v8
      with:
        message: 'chore: update douban data'
        add: './data/douban'