name: douban
on: 
  # schedule:
  # - cron: "0 0,0,12,23 * * *"
  # watch:
  #   types: [started]
  push:
    branches:
      - blog

jobs:
  douban:
    name: Syna Douban Data
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Sync Movies
      uses: lizheming/doumark-action@master
      with:
        id: 60029335
        type: movie
        format: json
        dir: ./themes/hugo-theme-stack/data/
    - name: Sync Books
      uses: lizheming/doumark-action@master
      with:
        id: 60029335
        type: book
        format: json
        dir: ./themes/hugo-theme-stack/data/
    - name: Auto Commit
      uses: EndBug/add-and-commit@v8
      with:
        message: 'Update Douban Data'
        add: ./themes/hugo-theme-stack/data/